/*
Navicat MySQL Data Transfer

Source Server         : PROD-Pugmarks
Source Server Version : 50642
Source Host           : 43.252.89.84 :3306
Source Database       : organization

Target Server Type    : MYSQL
Target Server Version : 50642
File Encoding         : 65001

Date: 2019-04-11 17:24:47
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `points_master`
-- ----------------------------
DROP TABLE IF EXISTS `points_master`;
CREATE TABLE `points_master` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category_id` int(11) DEFAULT NULL,
  `activity` text,
  `c1` int(11) DEFAULT NULL,
  `c2` int(11) DEFAULT NULL,
  `c3` int(11) DEFAULT NULL,
  `c4` int(11) DEFAULT NULL,
  `c5` int(11) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `points` int(11) DEFAULT NULL,
  `code` varchar(100) DEFAULT NULL,
  `activity_message_old` varchar(255) DEFAULT NULL,
  `activity_message` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_code` (`code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=179 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of points_master
-- ----------------------------
INSERT INTO `points_master` VALUES ('8', '1', 'User clicks the communities tab for the first time after installing the app', '1', '1', '1', '1', '1', '5', '50', 'CLICKS_COMMUNITY_TAB_FIRSTTIME', 'You clicked the community tab .', 'You visited the Communities platform for the first time!');
INSERT INTO `points_master` VALUES ('9', '1', 'User visits the communities tab any day (and scrolls at least one page during a session on each day)', '2', '1', '1', '2', '1', '7', '70', 'CLICKS_COMMUNITY_TAB_ANYDAY', 'You visited the community tab .', 'You visited the Communities platform on this day.');
INSERT INTO `points_master` VALUES ('10', '1', 'User visits & performs actions in the communities app after being inactive for a month', '1', '2', '2', '1', '0', '6', '60', 'USER_COMMUNITY_INACTIVE_MONTH', 'You visited the app after a month .', 'You visited the Communities platform after a month!');
INSERT INTO `points_master` VALUES ('11', '1', 'User joins \"X\" no. of communities in 30 days', '1', '2', '3', '1', '0', '7', '70', 'JOIN_X_COMMUNITY', 'You joined <counter> communities in 30 days.', 'You joined <counter> Communities in 30 days.');
INSERT INTO `points_master` VALUES ('12', '2', 'Auto-Joined Communities', '0', '0', '0', '0', '0', '0', '0', 'CLICK_AUTO_JOIN_COMMUNITIES', 'You are a part of auto-joined community <category_name>', 'You were automatically made a part of <category_name>  Community.');
INSERT INTO `points_master` VALUES ('13', '2', 'Join a Community which the user is not auto-joined to (only for first time)', '1', '2', '1', '3', '1', '8', '80', 'USER_JOIN_COMMUNITIES_FIRST_TIME', 'You joined a community <category_name>', 'You joined the  <category_name> Community.');
INSERT INTO `points_master` VALUES ('14', '2', 'Leave a community', '0', '0', '0', '0', '0', '0', '0', 'USER_LEAVE_COMMUNITIES', 'You left a community <category_name>', 'You left the <category_name> Community.');
INSERT INTO `points_master` VALUES ('15', '3', 'Subscribe to an Area of Interest which the user is not auto-subscribed to(only for first time)', '1', '3', '3', '4', '1', '12', '120', 'SUBSCRIBE_AOI_NON_AUTO_SUBSCRIBED', 'You subscribed to an AOI <category_name>', 'You subscribed to the  <category_name> AOI.');
INSERT INTO `points_master` VALUES ('16', '3', 'Unsubscribe from an Area of Interest', '0', '0', '0', '0', '0', '0', '0', 'UNSUBSCRIBE_AOI', 'You unsubscribed from an AOI <category_name>', 'You unsubscribed from the <category_name> AOI.');
INSERT INTO `points_master` VALUES ('17', '4', 'User created an open discussion', '1', '4', '4', '5', '4', '18', '180', 'USER_OPEN_DISCUSSION', 'You have created a discussion in <category_type> <category_name>', 'You created a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('18', '4', 'User created an invite-only discussion', '1', '3', '3', '2', '2', '11', '110', 'USER_INVITE_ONLY_DISCUSSION', 'You have created a invite-only discussion in <category_type> <category_name>', 'You created an invite-only discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('19', '4', 'User created an invisible discussion', '0', '2', '2', '1', '1', '6', '60', 'USER_INVISIBLE_DISCUSSION', 'You have created a invisible discussion in <category_type> <category_name>', 'You created an invisible discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('20', '4', 'User joined a discussion that is invite-only', '0', '0', '0', '0', '0', '0', '0', 'USER_JOINED_DISCUSSION_INVITE_ONLY', 'You joined a discussion that is invite-only in <category_type> <category_name>', 'You joined a discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('21', '4', 'User joined a discussion that is invisible', '0', '0', '0', '0', '0', '0', '0', 'USER_JOINED_DISCUSSION_INVISIBLE', 'You joined a invisible discussion in <category_type> <category_name>', 'You joined a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('22', '4', 'User who joined a discussion has chose to leave the discussion', '0', '0', '0', '0', '0', '0', '0', 'USER_CHOSE_LEAVE_DISCUSSION', 'You left a discussion in <category_type> <category_name>', 'You left a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('23', '4', 'User who created the discussion has chose to close the discussion', '0', '0', '0', '0', '0', '0', '0', 'USER_CHOSE_CLOSE_DISCUSSION', 'You closed a discussion in <category_type> <category_name>', 'You closed a discussion in the  <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('24', '4', 'User accepted requests for additional members for invite-only discussion', '0', '0', '1', '0', '0', '1', '10', 'USER_ACCEPT_REQUEST_ADDITIONAL_MEMBER', 'You accepted requests for additional members for discussion that is invite-only in <category_type> <category_name>', 'You added members in your discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('25', '4', 'User added additional members to the invite only discussion (through edit flow) ', '0', '0', '1', '0', '0', '1', '10', 'USER_ADDED_MEMBER_FOR_ONLY_DISCUSSION', 'You added additional members for discussion that is invite-only in <category_type> <category_name>', 'You added members in your discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('26', '4', 'User added additional members to the invisible discussion (through edit flow)', '0', '0', '1', '0', '0', '1', '10', 'ADDITIONAL_MEMBER_TO_INVISIBLE_DISCUSSION', 'You added additional members for a invisible discussion  in <category_type> <category_name>', 'You added members in your discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('27', '4', 'User removed members from the Discussion (invite-only)', '0', '0', '1', '0', '0', '1', '10', 'REMOVED_MEMBER_FROM_DISCUSSION', 'You removed members from a discussion that is invite-only in <category_type> <category_name>', 'You removed members from your discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('28', '4', 'User removed members from the Discussion (invisible)', '0', '0', '1', '0', '0', '1', '10', 'USER_REMOVED_MEMBERS_FROM_DIS_INVISIBLE', 'You removed members from a invisible discussion in <category_type> <category_name>', 'You removed members from your discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('29', '4', 'User creates a comment on an open discussion', '0', '2', '0', '2', '1', '5', '50', 'CREATE_COMMENT_OPEN_DISCUSSION', 'You have commented on an open discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('30', '4', 'User creates a comment on an invite only discussion', '0', '1', '0', '1', '0', '2', '20', 'COMMENT_ON_INVITE_ONLY_DISCUSSION', 'You have commented on an invite-only discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('31', '4', 'User creates a comment on an invisible discussion', '0', '1', '0', '0', '0', '1', '10', 'CREATE_COMMENT_ON_INVISIBLE_DISCUSSION', 'You have commented on an invisible discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('32', '4', 'User likes a comment posted on an open/invite-only/invisible discussion ', '0', '0', '0', '1', '0', '1', '10', 'USER_LIKE_COMMENT_ON_ALL_DISCUSSION', 'You liked a comment in a discussion in <category_type> <category_name>', 'You liked a comment in a discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('33', '4', 'User replied to a comment in Open Discussion', '0', '1', '0', '1', '1', '3', '30', 'REPLIED_TO_COMMENT_OPEN_DISCUSSION', 'You replied to a comment in an open discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('34', '4', 'User replied to a comment in invite-only discussion', '0', '1', '0', '1', '0', '2', '20', 'REPLIED_TO_COMMENT_INVITE_ONLY_DISCUSSION', 'You replied to a comment in an invite-only discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('35', '4', 'User replied to a comment in invisible discussion', '0', '1', '0', '0', '0', '1', '10', 'REPLIED_TO_COMMENT_INVISIBLE_DISCUSSION', 'You replied to a comment in an invisible discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('36', '4', 'User replied to a reply in an open discussion', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_OPEN_DISCUSSION', 'You replied to a reply in an open discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('37', '4', 'User replied to a reply in invite-only discussion', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_INVITE_ONLY_DISCUSSION', 'You replied to a reply in an invite-only discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('38', '4', 'User replied to a reply in invisible discussion', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_INVISIBLE_DISCUSSION', 'You replied to a reply in an invisible discussion in <category_type> <category_name>', 'You participated in a discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('39', '4', 'If action taken on a reported activity in a Discussion', '0', '2', '0', '2', '0', '4', '40', 'ACTION_TAKEN_REPORTED_ACTIVITY', 'Action was taken on you reported discussion in <category_type> <category_name>', 'A comment was removed from your discussion by the admin in <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('40', '4', 'Share a discussion (open/invite-only/invisible) with other people', '0', '0', '0', '0', '1', '1', '10', 'SHARE_DISCUSSION_WITH_OTHER', 'You shared a discussion in <category_type> <category_name>', 'You shared a discussion with your colleague.');
INSERT INTO `points_master` VALUES ('41', '4', 'Report a discussion (open/invite-only/invisible) and action has been taken successfully', '0', '0', '0', '0', '1', '1', '10', 'REPORT_DISCUSSION_AND_ACTION_TAKEN', 'You reported a discussion in <category_type> <category_name>', 'Action was taken on a discussion flagged by you in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('42', '4', 'SME/Leadership has endorsed a discussion (endorsement is basically that particular leadership/SME profile liking the post)', '0', '0', '0', '0', '1', '1', '10', 'SME_LEADERSHIP_ENDORSED', 'SME has endorsed a discussion in <category_type> <category_name>', 'An SME has endorsed your discussion in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('43', '4', '\'\"X\" discussions created across 30 days', '1', '3', '1', '4', '4', '13', '130', 'CREATED_DISCUSSION_ACROSS_30_DAYS', 'You created <counter> discussions across 30 days.', 'You created <counter> discussions in 30 days.');
INSERT INTO `points_master` VALUES ('44', '4', 'User created a discussion that has become trending', '0', '0', '0', '0', '0', '0', '0', 'DISCUSSION_BECOME_TRENDING', 'You created  a discussion that is trending.', 'Your discussion started trending!');
INSERT INTO `points_master` VALUES ('45', '4', 'Discussion received \"X\" comments', '0', '0', '0', '0', '0', '0', '0', 'DISCUSSION_RECEIVED_COMMENTS', 'Your discussion received <counter> comments.', 'Your discussion received <counter> comments.');
INSERT INTO `points_master` VALUES ('46', '5', 'User created an open poll successfully', '1', '1', '2', '0', '0', '4', '40', 'CREATED_OPEN_POLL', 'You created an open poll in <category_type> <category_name>', 'You started a poll in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('47', '5', 'User created an invite-only poll successfully', '0', '0', '0', '0', '0', '0', '0', 'USER_CREATED_INVITE_ONLY_POLL', 'You created an invite-only poll in <category_type> <category_name>', 'You started an invite-only poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('48', '5', 'User posts a comment on a poll', '0', '1', '0', '1', '1', '3', '30', 'POST_COMMENT_ON_POLL', 'You commented on a poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('49', '5', 'User likes a Comment/reply on a Poll', '0', '1', '0', '1', '0', '2', '20', 'USER_LIKE_COMMENT_ON_POLL', 'You liked a comment in a poll in <category_type> <category_name>', 'You liked a comment in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('50', '5', 'User replied to a comment posted in a poll', '0', '0', '0', '1', '0', '1', '10', 'USER_REPLIED_TO_COMMENT_IN_POLL', 'You replied on comment in a poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('51', '5', 'User replied to a reply posted on a poll', '0', '1', '0', '0', '0', '1', '10', 'USER_REPLIED_TO_REPLY_POSTED_POLL', 'You replied to a reply on a poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('52', '5', 'User reported  a poll and an action was taken successfully', '0', '2', '0', '2', '0', '4', '40', 'REPORTED_ON_POLL_ACTION_TAKEN', 'You reported a poll in <category_type> <category_name> and action was taken.', 'Action was taken on a poll flagged by you in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('53', '5', 'User added additional members to the invite-only poll (by going through the edit flow)', '0', '0', '0', '0', '0', '0', '0', 'ADDED_ADDITIONAL_MEMBER_TO_INVITE_ONLY_POLL', 'You added additional members in an invite-only poll in <category_type> <category_name>', 'You added members in your poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('54', '5', 'User removed members from an invite-only poll', '0', '0', '0', '0', '0', '0', '0', 'REMOVED_MEMBERS_FROM_INVITE_ONLY_POLL', 'You removed members in an invite-only poll in <category_type> <category_name>', 'You removed members from your poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('55', '5', 'User has posted a comment on a open poll', '1', '2', '2', '3', '3', '11', '110', 'POSTED_COMMENT_ON_OPEN_POLL', 'You have commented on an open poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('56', '5', 'User has posted a comment on a poll that is invite-only', '1', '1', '1', '2', '0', '5', '50', 'POSTED_COMMENT_ON_POLL_INVITE_ONLY', 'You have commented on an invite-only poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('57', '5', 'User likes a comment that is posted on the poll (open/invite-only/invisible)', '1', '1', '1', '1', '0', '4', '40', 'LIKE_COMMENT_POSTED_ON_POLL', 'You liked a comment on a poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('58', '5', 'User replied to a comment in an invite-only poll', '1', '1', '1', '1', '0', '4', '40', 'REPLIED_TO_COMMENT_INVITE_ONLY_POLL', 'You replied to a comment on an invite-only poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('59', '5', 'User replied to a reply in an open poll', '1', '1', '2', '2', '3', '9', '90', 'REPLIED_TO_REPLY_OPEN_POLL', 'You replied to a reply on an open poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('60', '5', 'User replied to a reply in an invite-only poll', '1', '1', '1', '0', '0', '3', '30', 'REPLIED_TO_REPLY_INVITE_ONLY_POLL', 'You replied to a reply on an invite-only poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('62', '5', 'User has particpated in the poll (open/invite-only) ', '0', '0', '0', '0', '0', '0', '0', 'USER_PARTICIPATED_POLL', 'You have participated in  a poll in <category_type> <category_name> .', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('63', '5', '\"X\" polls created across 30 days', '0', '1', '1', '0', '0', '2', '20', 'CREATED_POLL_ACROSS_30_DAYS', 'You have created <counter> polls in the last 30 days ', 'You created <counter> polls in 30 days.');
INSERT INTO `points_master` VALUES ('64', '5', 'User created a poll that has become trending', '0', '0', '0', '0', '0', '0', '0', 'CREATED_POLL_BECOME_TRENDING', 'Your poll in <category_type> <category_name>  is trending', 'Your poll started trending!');
INSERT INTO `points_master` VALUES ('65', '5', 'Poll received X comments', '0', '0', '0', '0', '0', '0', '0', 'POLL_RECEIVED_COMMENTS', 'Your poll received <counter> comments.', 'Your poll received <counter> comments.');
INSERT INTO `points_master` VALUES ('66', '6', 'User created an open poll successfully', '1', '1', '2', '0', '0', '4', '40', 'Created_OPEN_POLL_IN_AOI', 'You created an open poll in <category_type> <category_name>', 'You created a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('67', '6', 'User created an invite-only poll successfully', '0', '0', '0', '0', '0', '0', '0', 'CREATED_INVITE_ONLY_POLL_IN_AOI', 'You created an invite-only poll in <category_type> <category_name>', 'You created an invite-only poll in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('68', '6', 'User posts a comment on a poll', '0', '0', '0', '0', '0', '0', '0', 'POST_COMMENT_ON_POLL_IN_AOI', 'You commented on a poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('69', '6', 'User likes a Comment/reply on a Poll', '0', '0', '0', '0', '0', '0', '0', 'LIKE_COMMENT_ON_POLL_IN_AOI', 'You liked a comment in a poll in <category_type> <category_name>', 'You participated in a poll in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('70', '6', 'User replied to a comment posted in a poll', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_COMMENT_POSTED_IN_POLL_IN_AOI', 'You replied on comment in a poll in <category_type> <category_name>', 'You replied on comment in a poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('71', '6', 'User replied to a reply posted on a poll', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_ON_POLL_IN_AOI', 'You replied to a reply on a poll in <category_type> <category_name>', 'You replied to a reply on a poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('72', '6', 'User reported  a poll and an action was taken successfully ', '0', '0', '0', '0', '0', '0', '0', 'REPORTED_ON_POLL_ACTION_TAKEN_IN_AOI', 'You reported a poll in <category_type> <category_name> and action was taken.', 'You reported a poll in <category_type> <category_name> and action was taken.');
INSERT INTO `points_master` VALUES ('73', '6', 'User added additional members to the invite-only poll (by going through the edit flow)', '0', '0', '0', '0', '0', '0', '0', 'ADDED_ADDITIONAL_MEMBER_TO_INVITE_ONLY_POLL_IN_AOI', 'You added additional members in an invite-only poll in <category_type> <category_name>', 'You added additional members in an invite-only poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('74', '6', 'User removed members from an invite-only poll', '0', '0', '0', '0', '0', '0', '0', 'REMOVED_MEMBERS_FROM_INVITE_ONLY_POLL_IN_AOI', 'You removed members in an invite-only poll in <category_type> <category_name>', 'You removed members in an invite-only poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('75', '6', 'User has posted a comment on a open poll', '0', '0', '0', '0', '0', '0', '0', 'POSTED_COMMENT_ON_OPEN_POLL_IN_AOI', 'You have commented on an open poll in <category_type> <category_name>', 'You have commented on an open poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('76', '6', 'User has posted a comment on a poll that is invite-only', '0', '0', '0', '0', '0', '0', '0', 'POSTED_COMMENT_ON_POLL_INVITE_ONLY_IN_AOI', 'You have commented on an invite-only poll in <category_type> <category_name>', 'You have commented on an invite-only poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('77', '6', 'User likes a comment that is posted on the poll (open/invite-only/invisible)', '0', '0', '0', '0', '0', '0', '0', 'LIKE_COMMENT_POSTED_ON_POLL_IN_AOI', 'You liked a comment on a poll in <category_type> <category_name>', 'You liked a comment on a poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('78', '6', 'User replied to a comment in an invite-only poll', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_COMMENT_INVITE_ONLY_POLL_IN_AOI', 'You replied to a comment on an invite-only poll in <category_type> <category_name>', 'You replied to a comment on an invite-only poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('79', '6', 'User replied to a reply in an open poll', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_OPEN_POLL_AOI', 'You replied to a reply on an open poll in <category_type> <category_name>', 'You replied to a reply on an open poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('80', '6', 'User replied to a reply in an invite-only poll', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_INVITE_ONLY_POLL_AOI', 'You replied to a reply on an invite-only poll in <category_type> <category_name>', 'You replied to a reply on an invite-only poll in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('82', '6', 'User has particpated in the poll (open/invite-only)', '0', '0', '0', '0', '0', '0', '0', 'USER_PARTICIPATED_IN_POLL_IN_AOI', 'You have participated in  a poll in <category_type> <category_name> .', 'You have participated in  a poll in <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('83', '6', '\"X\" polls created across 30 days', '1', '1', '1', '1', '0', '4', '40', 'POLLS_CREATED_ACROSS_30_DAYS_IN_AOI', 'You have created <counter> polls in the last 30 days ', 'You have created <counter> polls in the last 30 days ');
INSERT INTO `points_master` VALUES ('84', '6', 'User created a poll that has become trending', '0', '0', '0', '0', '0', '0', '0', 'CREATED_POLL_BECOMING_TRENDING_IN_AOI', 'Your poll in <category_type> <category_name>  is trending', 'Your poll in <category_type> <category_name>  is trending');
INSERT INTO `points_master` VALUES ('85', '6', 'Poll received X comments', '0', '0', '0', '0', '0', '0', '0', 'POLL_RECEIVED_COMMENTS_IN_AOI', 'Your poll received <counter> comments.', 'Your poll received <counter> comments.');
INSERT INTO `points_master` VALUES ('86', '7', 'User scheduled an open event', '4', '2', '4', '4', '1', '15', '150', 'USER_SCHEDULED_OPEN_EVENT_AOI', 'You scheduled an open event in <category_type> <category_name>', 'You scheduled an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('87', '7', 'User scheduled an invite-only event', '1', '1', '2', '2', '1', '7', '70', 'USER_SCHEDULED_INVITE_ONLY_EVENT_AOI', 'You scheduled an invite-only event in <category_type> <category_name>', 'You scheduled an invite-only event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('88', '7', 'User scheduled an invisible event ', '0', '1', '2', '2', '1', '6', '60', 'USER_SCHEDULED_INVISIBLE_EVENT_AOI', 'You scheduled an invisible event in <category_type> <category_name>', 'You scheduled an invisible event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('89', '7', 'User added additional members to the invite-only event (by going through the edit flow)', '1', '0', '1', '1', '0', '3', '30', 'ADDED_ADDITIONAL_MEMBERS_TO_INVITE_ONLY_EVENT', 'You added additional members in an invite-only event in <category_type> <category_name>', 'You invited additional people to your event in the <category_type> <category_name>  .');
INSERT INTO `points_master` VALUES ('90', '7', 'User added additional members to the invisible event (by going through the edit flow)', '0', '0', '1', '1', '0', '2', '20', 'ADDED_ADDITIONAL_MEMBERS_TO_INVISIBLE_EVENT', 'You added additional members in an invisible event in <category_type> <category_name>', 'You invited additional people to your event in the <category_type> <category_name>  .');
INSERT INTO `points_master` VALUES ('91', '7', 'User removed members from an invite-only event ', '0', '0', '0', '0', '0', '0', '0', 'REMOVED_MEMBERS_FROM_INVITE_ONLY_EVENT', 'You removed members in an invite-only event in <category_type> <category_name>', 'You removed people from your event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('92', '7', 'User removed members from an invisible event ', '0', '0', '0', '0', '0', '0', '0', 'REMOVED_MEMBERS_FROM_INVISIBLE_EVENT', 'You removed members in an invisible event in <category_type> <category_name>', 'You removed people from your event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('93', '7', 'User has posted a comment on an open event ', '0', '2', '0', '3', '3', '8', '80', 'POSTED_COMMENT_ON_OPEN_EVENT', 'You commented on an open event  in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('94', '7', 'User has posted a comment on an event that is invite-only', '0', '2', '0', '2', '1', '5', '50', 'POSTED_COMMENT_ON_INVITE_ONLY_EVENT', 'You commented on an invite-only event  in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('95', '7', 'User has posted a comment on an event that is invisible ', '0', '2', '0', '1', '0', '3', '30', 'POSTED_COMMENT_ON_INVISIBLE_EVENT', 'You commented on an invisible event  in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('96', '7', 'User likes a comment that is posted on the event (open/invite-only/invisible)', '0', '0', '0', '1', '0', '1', '10', 'USER_LIKES_COMMENT_POSTED_ON_EVENT', 'You liked a comment on an event in <category_type> <category_name>', 'You liked a comment in an event in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('97', '7', 'User replied to a comment in an invite-only event ', '0', '2', '0', '2', '1', '5', '50', 'USER_REPLIED_TO_COMMENT_IN_INVITE_ONLY_EVENT', 'You liked a comment on an invite-only event in <category_type> <category_name>', 'You liked a comment in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('98', '7', 'User replied to a comment in an invisible event ', '0', '1', '0', '1', '1', '3', '30', 'USER_REPLIED_TO_COMMENT_IN_INVISIBLE_EVENT', 'You liked a comment on an invisible event in <category_type> <category_name>', 'You liked a comment in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('99', '7', 'User replied to a reply in an open event ', '0', '0', '0', '0', '1', '1', '10', 'REPLIED_TO_REPLY_IN_OPEN_EVENT', 'You replied to a reply in an open event in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('100', '7', 'User replied to a reply in an invite-only event ', '0', '0', '0', '0', '1', '1', '10', 'REPLIED_TO_REPLY_IN_INVITE_ONLY_EVENT', 'You replied to a reply in an invite-only event in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('101', '7', 'User replied to a reply in an invisible event', '0', '0', '0', '0', '1', '1', '10', 'REPLIED_TO_REPLY_IN_INVISIBLE_EVENT', 'You replied to a reply in an invisible event in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> ');
INSERT INTO `points_master` VALUES ('102', '7', 'User replies to a reply in an open event ', '0', '0', '1', '0', '2', '3', '30', 'REPLIES_TO_REPLY_IN_OPEN_EVENT', 'You have commented on a blog in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('103', '7', 'User replies to a reply in an invite-only event ', '0', '0', '1', '0', '1', '2', '20', 'REPLIES_TO_REPLY_IN_INVITE_ONLY_EVENT', 'You have commented on a blog in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('104', '7', 'User replies to a reply in an invisible event ', '0', '0', '0', '0', '1', '1', '10', 'REPLIES_TO_REPLY_IN_INVISIBLE_EVENT', 'You have commented on a blog in <category_type> <category_name>', 'You participated in an event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('105', '7', 'User has reported an event and action has been successfully taken by the admin', '0', '2', '0', '2', '0', '4', '40', 'USER_REPORTED_EVENT_ACTION_TAKEN_ADMIN', 'You reported an event in <category_type> <category_name> and action was taken.', 'Action was taken on an event flagged by you in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('106', '7', 'User has RSVP\'d to the event (open/invite-only/invisible) ', '0', '0', '0', '1', '1', '2', '20', 'USER_RSVP_EVENT', 'You RSVP\'d to an event in <category_type> <category_name>', 'You indicated \"Going\" to an event in the <category_type><category_name> .');
INSERT INTO `points_master` VALUES ('107', '7', 'User has given feedback for an event that he/she attended', '0', '0', '0', '0', '0', '0', '0', 'USER_GIVEN_FEEDBACK_FOR_ATTENDED_EVENT', 'You have given feedback on an event in <category_type> <category_name>', 'You provided your feedback for an event you attended in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('108', '7', '\'\"X\" users are attending the event (open/invite-only/invisible) created by user', '0', '2', '0', '0', '0', '2', '20', 'USERS_ATTENDING_EVENT_CREATED_BY_USER', 'You have commented on a blog in <category_type> <category_name>', 'You have commented on a blog in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('109', '7', '\'\"X\" events created in a span of 30 days', '0', '2', '2', '3', '4', '11', '110', 'EVENTS_CREATED_IN_30_DAYS', 'You have created <counter> events in the last 30 days', 'You created <counter> events in 30 days.');
INSERT INTO `points_master` VALUES ('110', '7', 'User creates an event that is trending', '0', '0', '0', '0', '0', '0', '0', 'USER_CREATES_TRENDING_EVENTS', 'You have created a event that is trending in <category_type> <category_name>', 'Your event started trending!');
INSERT INTO `points_master` VALUES ('111', '7', 'Event received X comments', '0', '0', '0', '0', '0', '0', '0', 'EVENT_RECEIVED_COMMENTS', 'You received <counter> comments  on events.', 'You received <counter> comments  on events.');
INSERT INTO `points_master` VALUES ('112', '7', 'SME endorses an event (open/invite-only/invisible)', '0', '0', '0', '0', '1', '1', '10', 'SME_ENDORSES_EVENT', 'SME has endorsed an event in <category_type> <category_name>', 'An SME endorsed your event in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('113', '8', 'User scheduled an open event', '1', '1', '2', '2', '2', '8', '80', 'SCHEDULED_OPEN_EVENT_COMMUNITIES', 'You scheduled an open event in <category_type> <category_name>', 'You scheduled an open event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('114', '8', 'User scheduled an invite-only event', '0', '0', '0', '0', '0', '0', '0', 'SCHEDULED_INVITE_ONLY_EVENT_COMMUNITIES', 'You scheduled an invite-only event in <category_type> <category_name>', 'You scheduled an invite-only event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('115', '8', 'User scheduled an invisible event ', '0', '0', '0', '0', '0', '0', '0', 'SCHEDULED_INVISIBLE_EVENT_COMMUNITIES', 'You scheduled an invisible event in <category_type> <category_name>', 'You scheduled an invisible event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('116', '8', 'User added additional members to the invite-only event (by going through the edit flow)', '0', '0', '0', '0', '0', '0', '0', 'ADDITIONAL_MEMBERS_TO_INVITE_ONLY_EVENT_COM', 'You added additional members in an invite-only event in <category_type> <category_name>', 'You added additional members in an invite-only event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('117', '8', 'User added additional members to the invisible event (by going through the edit flow)', '0', '0', '0', '0', '0', '0', '0', 'ADDITIONAL_MEMBERS_TO_INVISIBLE_EVENT_COM', 'You added additional members in an invisible event in <category_type> <category_name>', 'You added additional members in an invisible event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('118', '8', 'User removed members from an invite-only event ', '0', '0', '0', '0', '0', '0', '0', 'REMOVED_MEMBERS_FROM_INVITE_ONLY_EVENT_COM', 'You removed members in an invite-only event in <category_type> <category_name>', 'You removed members in an invite-only event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('119', '8', 'User removed members from an invisible event ', '0', '0', '0', '0', '0', '0', '0', 'REMOVED_MEMBERS_FROM_INVISIBLE_EVENT_COM', 'You removed members in an invisible event in <category_type> <category_name>', 'You removed members in an invisible event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('120', '8', 'User has posted a comment on a open event ', '0', '0', '0', '0', '0', '0', '0', 'POSTED_COMMENT_ON_OPEN_EVENT_COM', 'You commented on an open event  in <category_type> <category_name>', 'You commented on an open event  in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('121', '8', 'User has posted a comment on an event that is invite-only', '0', '0', '0', '0', '0', '0', '0', 'POSTED_COMMENT_ON_INVITE_ONLY_EVENT_COM', 'You commented on an invite-only event  in <category_type> <category_name>', 'You commented on an invite-only event  in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('122', '8', 'User has posted a comment on an event that is invisible ', '0', '0', '0', '0', '0', '0', '0', 'POSTED_COMMENT_ON_INVISIBLE_EVENT_COM', 'You commented on an invisible event  in <category_type> <category_name>', 'You commented on an invisible event  in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('123', '8', 'User likes a comment that is posted on the event ', '0', '0', '0', '0', '0', '0', '0', 'LIKES_COMMENT_POSTED_ON_EVENT_COM', 'You liked a comment on an event in <category_type> <category_name>', 'You liked a comment on an event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('124', '8', 'User replied to a comment in an invite-only event ', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_COMMENT_IN_INVITE_ONLY_EVENT_COM', 'You liked a comment on an invite-only event in <category_type> <category_name>', 'You liked a comment on an invite-only event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('125', '8', 'User replied to a comment in an invisible event ', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_COMMENT_IN_INVISIBLE_EVENT_COM', 'You liked a comment on an invisible event in <category_type> <category_name>', 'You liked a comment on an invisible event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('126', '8', 'User replied to a reply in an open event ', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_IN_OPEN_EVENT_COM', 'You replied to a reply in an open event in <category_type> <category_name>', 'You replied to a reply in an open event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('127', '8', 'User replied to a reply in an invite-only event ', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_IN_INVITE_ONLY_EVENT_COM', 'You replied to a reply in an invite-only event in <category_type> <category_name>', 'You replied to a reply in an invite-only event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('128', '8', 'User replied to a reply in an invisible event', '0', '0', '0', '0', '0', '0', '0', 'REPLIED_TO_REPLY_IN_INVISIBLE_EVENT_COM', 'You replied to a reply in an invisible event in <category_type> <category_name>', 'You replied to a reply in an invisible event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('129', '8', 'User has reported an event and action has been successfully taken by the admin', '0', '0', '0', '0', '0', '0', '0', 'REPORTED_EVENT_ACTION_TAKEN_ADMIN_COM', 'You reported an event in <category_type> <category_name> and action was taken.', 'You reported an event in <category_type> <category_name> and action was taken.');
INSERT INTO `points_master` VALUES ('130', '8', 'User has RSVP\'d to the event (open/invite-only/invisible)', '0', '0', '0', '0', '0', '0', '0', 'USER_RSVP_EVENT_COM', 'You RSVP\'d to an event in <category_type> <category_name>', 'You RSVP\'d to an event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('131', '8', 'User has given feedback for an event that he/she attended', '0', '0', '0', '0', '0', '0', '0', 'GIVEN_FEEDBACK_FOR_ATTENDED_EVENT_COM', 'You have given feedback on an event in <category_type> <category_name>', 'You have given feedback on an event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('132', '7', '\'\"X\" users are attending the event (open/invite-only/invisible) created by user', '0', '0', '0', '0', '0', '0', '0', 'USERS_ATTENDING_EVENT_CREATED_BY_USER_COM', '<counter> users are attending an event in <category_type> <category_name>', '<counter> users are attending an event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('133', '8', '\'\"X\" events created in a span of 30 days', '0', '0', '0', '0', '0', '0', '0', 'EVENTS_CREATED_IN_30_DAYS_COM', 'You have created <counter> events in the last 30 days', 'You have created <counter> events in the last 30 days');
INSERT INTO `points_master` VALUES ('134', '8', 'User creates an event that is trending', '0', '0', '0', '0', '0', '0', '0', 'CREATES_TRENDING_EVENT_COM', 'You have created a event that is trending in <category_type> <category_name>', 'You have created a event that is trending in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('135', '8', 'User reported a comment on an event ', '0', '0', '0', '0', '0', '0', '0', 'REPORTED_COMMENT_ON_EVENT_COM', 'You have reported a comment on a event in <category_type> <category_name>', 'You have reported a comment on a event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('136', '8', 'SME endorses an event (open/invite-only/invisible)', '0', '0', '0', '0', '0', '0', '0', 'SME_ENDORSES_EVENT_COM', 'SME has endorsed an event in <category_type> <category_name>', 'SME has endorsed an event in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('137', '8', 'Event received X comments', '0', '0', '0', '0', '0', '0', '0', 'EVENT_RECEIVED_COMMENTS_COM', 'You received <counter> comments  on events.', 'You received <counter> comments  on events.');
INSERT INTO `points_master` VALUES ('138', '7', 'User reported a comment on an event and action has been taken successfully ', '0', '0', '0', '1', '1', '2', '20', 'REPORTED_COMMENT_ON_EVENT_ACTION_TAKEN_SUCCESSFULLY', 'You have reported a comment on a event in <category_type> <category_name>', 'Action was taken on a comment flagged by you in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('139', '12', 'User published a full blog successfully', '0', '5', '0', '4', '1', '10', '100', 'PUBLISHED_FULL_BLOG', 'You published a blog in <category_type> <category_name>', 'You published a blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('140', '12', 'User published a short blog successfully', '0', '0', '0', '1', '1', '2', '20', 'PUBLISHED_SHORT_BLOG', 'You published a short blog in <category_type> <category_name>', 'You published a short blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('141', '12', 'User posted a comment on a full blog ', '0', '2', '0', '1', '0', '3', '30', 'POSTED_COMMENT_ON_FULL_BLOG', 'You commented on a full blog in <category_type> <category_name>', 'You commented on a blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('142', '12', 'User posted a comment on a short blog', '0', '2', '0', '1', '0', '3', '30', 'POSTED_COMMENT_ON_SHORT_BLOG', 'You commented on a short blog in <category_type> <category_name>', 'You commented on a blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('143', '12', 'User likes a comment posted on full blog ', '0', '0', '0', '1', '0', '1', '10', 'LIKES_COMMENT_ON_FULL_BLOG', 'You liked a comment on a full blog in <category_type> <category_name>', 'You liked a comment on a blog in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('144', '12', 'User likes a comment posted on short blog', '0', '0', '2', '1', '1', '4', '40', 'LIKES_COMMENT_ON_SHORT_BLOG', 'You liked a comment on a short blog in <category_type> <category_name>', 'You liked a comment on a blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('145', '12', 'User replied to a comment posted in a full blog ', '0', '1', '0', '1', '0', '2', '20', 'REPLIED_TO_COMMENT_IN_FULL_BLOG', 'You replied on a comment in a full blog in <category_type> <category_name>', 'You commented on a blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('146', '12', 'User replied to a comment posted in a short blog ', '0', '0', '1', '0', '1', '2', '20', 'REPLIED_TO_COMMENT_IN_SHORT_BLOG', 'You replied on a comment in a short blog in <category_type> <category_name>', 'You commented on a blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('147', '12', 'User replied to a reply posted in a full blog ', '0', '0', '1', '0', '1', '2', '20', 'REPLIED_TO_REPLY_IN_FULL_BLOG', 'You commented on a blog in <category_type> <category_name>', 'You commented on a blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('148', '12', 'User replied to a reply posted in a short blog', '0', '0', '1', '0', '1', '2', '20', 'REPLIED_TO_REPLY_IN_SHORT_BLOG', 'You commented on a blog in <category_type> <category_name>', 'You commented on a blog in the <category_type> <category_name> .');
INSERT INTO `points_master` VALUES ('149', '12', 'User read a full blog/micro blog ', '0', '0', '0', '0', '0', '0', '0', 'READ_FULL_BLOG_MICRO_BLOG', 'You read  a full blog in <category_type> <category_name>', 'You read  a full blog in <category_type> <category_name>');
INSERT INTO `points_master` VALUES ('150', '12', 'User reported a comment posted on full blog/micro blog', '1', '1', '1', '1', '0', '4', '40', 'REPORTED_COMMENT_ON_FULL_BLOG_MICRO_BLOG', 'You reported a comment on a blog in <category_type> <category_name>', 'You reported a comment on a blog in the <category_type> <category_name>.');
INSERT INTO `points_master` VALUES ('151', '12', 'If action taken on a reported activity in a blog (full/micro)', '0', '2', '0', '2', '0', '4', '40', 'ACTION_TAKEN_REPORTED_ACTIVITY_IN_BLOG', 'Action is taken on a reported blog in <category_type> <category_name>', 'Action was taken on a comment flagged by you in the <category_type> <category_name> ');
INSERT INTO `points_master` VALUES ('152', '12', 'Share a blog (full/micro) by a user', '0', '0', '0', '0', '0', '0', '0', 'SHARE_BLOG_BY_USER', 'You shared a blog in <category_type> <category_name>', 'You shared a blog with your colleague.');
INSERT INTO `points_master` VALUES ('153', '12', '\'\"X\" blogs published in a span of 30 days', '1', '3', '2', '3', '4', '13', '130', 'BLOGS_PUBLISHED_IN_30_DAYS', 'You commented on a blog in <category_type> <category_name>', 'You published <counter> blogs in 30 days.');
INSERT INTO `points_master` VALUES ('154', '12', 'Blog published by user becomes trending', '1', '2', '2', '4', '4', '13', '130', 'PUBLISHED_BLOG_BECOMES_TRENDING', 'Your blog in <category_type> <category_name> is trending', 'Your blog started trending!');
INSERT INTO `points_master` VALUES ('155', '12', 'SME endorses a full/micro blog that is posted', '0', '0', '0', '0', '0', '0', '0', 'SME_ENDORSES_FULL_MICRO_BLOG', 'You commented on a blog in <category_type> <category_name>', 'An SME endorsed your blog!');
INSERT INTO `points_master` VALUES ('156', '12', 'Blog received X comments', '0', '0', '0', '0', '0', '0', '0', 'BLOG_RECEIVED_COMMENTS', 'Your blog in <category_type> <category_name> received <comment_counter> comments.', 'Your blog received <comment_counter> comments.');
INSERT INTO `points_master` VALUES ('157', '9', 'Connect with People', '3', '0', '0', '0', '0', '3', '30', 'CONNECT_WITH_PEOPLE', 'You connected with <user>', 'You connected with <user>');
INSERT INTO `points_master` VALUES ('158', '9', 'Follow People', '0', '3', '0', '0', '0', '3', '30', 'FOLLOW_PEOPLE', 'You followed <user>', 'You started following <user>.');
INSERT INTO `points_master` VALUES ('159', '9', 'User\'s Bio (edited/updated)', '1', '0', '0', '1', '0', '2', '20', 'USERS_BIO', 'You updated your bio', 'You updated your bio.');
INSERT INTO `points_master` VALUES ('160', '9', 'Any content is bookmarked', '0', '0', '0', '0', '0', '0', '0', 'CONTENT_IS_BOOKMARKED', 'You bookmarked a  <content>', 'You bookmarked a <content>');
INSERT INTO `points_master` VALUES ('161', '10', 'User searches for people ', '0', '0', '0', '0', '0', '0', '0', 'USER_SEARCHES_PEOPLE', 'You searched for <user>', 'You searched for <user>');
INSERT INTO `points_master` VALUES ('162', '10', 'User searches for blogs', '0', '0', '0', '0', '0', '0', '0', 'USER_SEARCHES_BLOGS', 'You searched for a blog.', 'You searched for a blog.');
INSERT INTO `points_master` VALUES ('163', '10', 'User searches for communities', '0', '0', '0', '0', '0', '0', '0', 'USER_SEARCHES_COMMUNITIES', 'You searched for a community.', 'You searched for a community.');
INSERT INTO `points_master` VALUES ('164', '10', 'User searches for AOIs', '0', '0', '0', '0', '0', '0', '0', 'USER_SEARCHES_AOI', 'You searched for a AOI.', 'You searched for a AOI.');
INSERT INTO `points_master` VALUES ('165', '10', 'User searches for discussions', '0', '0', '0', '0', '0', '0', '0', 'USER_SEARCHES_DISCUSSIONS', 'You searched for a discussion.', 'You searched for a discussion.');
INSERT INTO `points_master` VALUES ('166', '10', 'User searches for events', '0', '0', '0', '0', '0', '0', '0', 'USER_SEARCHES_EVENTS', 'You searched for a event.', 'You searched for a event.');
INSERT INTO `points_master` VALUES ('167', '10', 'User searches for polls', '0', '0', '0', '0', '0', '0', '0', 'USER_SEARCHES_POLLS', 'You searched for a poll.', 'You searched for a poll.');
INSERT INTO `points_master` VALUES ('168', '11', 'User has given a personality assessment test', '0', '0', '0', '0', '0', '0', '0', 'USER_GIVEN_PERSONALITY_ASSESSMENT_TEST', 'You gave a personality assessment test.', 'You gave a personality assessment test.');
INSERT INTO `points_master` VALUES ('169', '11', 'User has applied an Avatar ', '0', '0', '0', '0', '0', '0', '0', 'USER_APPLIED_AVATAR', 'You applied an Avatar ', 'You selected your Avatar.');
INSERT INTO `points_master` VALUES ('170', '11', 'User has customized his avatar ', '0', '0', '0', '0', '0', '0', '0', 'USER_CUSTOMIZED_AVATAR', 'You customized an Avatar ', 'You customized your Avatar.');
INSERT INTO `points_master` VALUES ('171', '11', 'User has completed certain milestones in his user journey ', '0', '0', '0', '0', '0', '0', '0', 'USER_COMPLETED_MILESTONES_IN_JOURNEY', 'You completed a milestone in your journey', 'You hit a new milestone in your journey on the Communities platform.');
INSERT INTO `points_master` VALUES ('172', '13', 'logging in once every week', '1', '0', '0', '0', '0', '1', '10', 'LOGGING_ONCE_A_WEEK', 'You logged in once this week.', 'You logged in once this week.');
INSERT INTO `points_master` VALUES ('173', '13', 'logging in every day of the week ', '2', '2', '1', '0', '0', '5', '50', 'LOGGING_EVERYDAY_OF_A_WEEK', 'You logged in every day this week.', 'You logged in every day this week.');
INSERT INTO `points_master` VALUES ('174', '14', 'User loses points if he doesn\'t log-in continuously for 15 days ', '2', '2', '2', '2', '2', '10', '100', 'NO_LOGIN_15DAYS', 'You did not log-in for last 15 days', 'You did not log-in for last 15 days');
INSERT INTO `points_master` VALUES ('175', '15', ' extra points with each level unlock.', '2', '2', '2', '2', '2', '10', '100', 'UNLOCK_LEVEL', 'You unlocked a new level.', 'You unlocked a new level.');
